### ISSUE TITLE
How can I specify asset file with country code (like `en-US`, `en-UK`)?

### ISSUE THREAD

**Issue by trietbui85** [Jesway/flutter_translate#11]
I notice some localization library for Flutter supports naming like `languageCode-countryCode` (for example `en-US`, `en-UK`) but this library doesn't. Can you add support for it?

**Comment by bratan** [comment]
The library supports it, but you need to specify the format as ```languageCode_countryCode``` (underline instead of dash)

For example: ```en_US```, ```en_GB```, ```es_ES```

It will also automatically fallback to languageCode for the filename.

So for example if you define the supported locales this way:

```sh
supportedLocales: ['en_US', 'en_GB', 'es_ES'])
```

It will search for the filenames ```en_US.json```, ```en_GB.json``` ... and if not found, it will fallback to ```en.json```

I will have to update the documentation as there are some more features not yet documented properly.

**Comment by trietbui85** [comment]
@bratan Thanks for your answer. It's great to know that feature is already supported yet.
